### ISSUE TITLE
Multiple search requests triggered with rangeSlider widget

### ISSUE THREAD

**Issue by sabatale** [meilisearch/instant-meilisearch#1033]
Hello,

While setting up rangeSlider components, we realized a surge in the number of search requests. It looks like, whenever we configure a rangeSlider instead of a standard refinementList widget, instantsearch triggers an additional request.

E.g.,

Let's assume this is the default instantsearch.configure():

```
var defaultConfig = {
  hitsPerPage: 20,
  filters: ''
};

var filters = localStorage.getItem('instant');
if (filters) {
  defaultConfig.filters = filters;
} else {
  localStorage.setItem('instant', 'price EXISTS');
  filters = localStorage.getItem('instant');
  defaultConfig.filters = filters;
}

...
instantsearch.widgets.configure(defaultConfig),
...
```
If we setup a refinementList such as:

```
        instantsearch.widgets.refinementList({
          container: '#rooms-slider',
          attribute: 'rooms',
          sortBy: ['name:asc'],
        }),
```
This triggers the following on search.start():

`{"q":"","facets":["rooms", ...],"hitsPerPage":20,"page":1}`

While adding a rangeSlider such as:

```
        instantsearch.widgets.rangeSlider({
          container: '#rooms-slider',
          attribute: 'rooms',
          min: 0,
          max: 10,
          pips: false,
          cssClasses: {
            root: 'myPriceSlider'
          }
        }),
```

triggers the previous request, but also:

`{"q":"","facets":["rooms"],"attributesToHighlight":["*"],"highlightPreTag":"__ais-highlight__","highlightPostTag":"__/ais-highlight__","hitsPerPage":0,"page":1,"filter":["price EXISTS"]}`

It looks clear this has something to do with the highlighting but we were unable to figure out how to disable that particular behaviour, other than using a refinementList widget (at the cost of poor UX).

Can you please clarify if this is normal behaviour with the rangeSlider? In other words, setting up 10 rangeSlider widgets will result in 11 fetch requests per search?

Cheers,

**Comment by bidoubiwa** [comment]
Hey @sabatale, indeed this is an expected behavior for us to try out the new facet count behavior. As per the [release body](https://github.com/meilisearch/instant-meilisearch/releases/tag/%40meilisearch%2Finstant-meilisearch%400.11.0) of v0.11.0, we mentioned the drawback being the additional HTTP requests. Maybe it should have not been released on production. Meanwhile you can rollback to the previous version of instant meilisearch (v0.10.0) which should fix this issue.

But! good news :D In the next version of Meilisearch (v1.1), instant-meilisearch will be updated and only `one` request will be done on search, whatever number of sliders or refinementlist you use.

**Comment by sabatale** [comment]
Thanks for the update, great news indeed. We'll definitely rollback in the meantime.
