### ISSUE TITLE
Images of the demos are broken on Chrome

### ISSUE THREAD

**Issue by curquiza** [meilisearch/instant-meilisearch#148]
The images are broken on Chrome only for:
- https://sh9ud.csb.app/
- https://mese9.csb.app/
- https://1d6bi.csb.app/

**Comment by bidoubiwa** [comment]
This issue is due to what is commonly called `mixed content problem`. In which some website that have a valid SSL certificate imports resources in `http`. Which compromises the security of the website. 
More about that here: https://blog.cloudflare.com/fixing-the-mixed-content-problem-with-automatic-https-rewrites/

Chromium decided to not send mixed messages (cf say that a website is secure when it is in fact importing not secure resources) by forcing every `https` website to only fetch `https` ressources. 

> Today we’re announcing that Chrome will gradually start ensuring that https:// pages can only load secure https:// subresources. In a series of steps outlined below, we’ll start blocking mixed content (insecure http:// subresources on https:// pages) by default. This change will improve user privacy and security on the web, and present a clearer browser security UX to users.
[More information here](https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html)

Because of the images used in this sandbox are all `http` they are thus transformed into https: 
<img width="847" alt="Screenshot 2020-11-18 at 11 27 52" src="https://user-images.githubusercontent.com/33010418/99518736-4932e100-2991-11eb-8522-36f393cfdbfe.png">

The changes from `http` to  `https` are mentioned in this warning :

<img width="1273" alt="Screenshot 2020-11-18 at 11 22 23" src="https://user-images.githubusercontent.com/33010418/99518809-5cde4780-2991-11eb-8e92-83a8711adb6b.png">

To fix this problem, we will need to have `https` links to the images.

**Comment by curquiza** [comment]
We are going to deploy a proxy to transfer the `https` requests into `http` ones in order to fix this issue.

**Comment by curquiza** [comment]
Everything seems ok now, can you confirm @bidoubiwa or @eskombro?

**Comment by bidoubiwa** [comment]
Good for me

**Comment by curquiza** [comment]
Closing this issue then! 🚀
