### ISSUE TITLE
question: incompatible meilisearch versions

### ISSUE THREAD

**Issue by meck93** [meilisearch/instant-meilisearch#150]
First of all, thanks for the great work on meilisearch. It's a really awesome product. 

I have a question or a remark regarding upgrading. Today, I upgrade from: `@meilisearch/instant-meilisearch: 0.2.2 → 0.2.4`. On the server-side, we were using `meilisearch: 0.16.1` and the meilisearch instance was running `meilisearch-http: 0.14`. This broke the setup for us. Everything was still working but the queries no longer returned any hits. Once I upgrade to `meilisearch: 0.16` everything worked fine again once I had deleted and re-created the index. 

**question:** can we make a note somewhere so that if someone else experiences this issue that we have it documented? Or is it always the case that old client versions cannot query newer server versions? Because vice versa worked fine for us. For example, we had upgraded to `meilisearch: 0.16.1` on our nodejs backend and it worked fine with `meilisearch-http: 0.14`. 

Thanks for the feedback. Would love to help if I can improve some documentation!

**Comment by curquiza** [comment]
Hello @meck93!
Glad to read you love MeiliSearch 😁

> can we make a note somewhere so that if someone else experiences this issue that we have it documented? Or is it always the case that old client versions cannot query newer server versions?

The SDKs we release (like [`meilisearch-js`](https://github.com/meilisearch/meilisearch-js) and [`instant-meilisearch`](https://github.com/meilisearch/instant-meilisearch)) are always done and maintained for the latest release of MeiliSearch server (or `meilisearch-http` in your issue). See the section in all the SDKs README: https://github.com/meilisearch/instant-meilisearch#compatibility-with-meilisearch.
However, the changes between the two versions of the MeiliSearch do not always impact all the routes: it means sometimes breakable changes in MeiliSearch do not impact your code-base but might impact the code-base of other users. That's why, sometimes, you can use an old MeiliSearch server version with the newest client version, and vice versa.
And that's why we recommend always using the latest version of MeiliSearch and the latest version of the SDKs/clients/plugins. This might be complicated, we know that, but the changes we are doing fix a lot of bugs, so upgrading MeiliSearch server and its integration tools is definitely a good choice!
Since we are not stable yet, we are doing a lot of releases (at least one per month), so we can't afford to maintain a note about the differents version compatibilities, sorry about that!

Hope I answered your question!

**Comment by meck93** [comment]
Hi @curquiza 

Thanks a lot for answering my questions. 
> Since we are not stable yet, we are doing a lot of releases (at least one per month), so we can't afford to maintain a note about the different version compatibilities, sorry about that!

That totally makes sense. I keep forgetting that meili has not officially reached a stable version yet. So, I guess upgrade guides are going to be a topic for the future once meili has reached a stable version.

**Comment by curquiza** [comment]
> So, I guess upgrade guides are going to be a topic for the future once meili has reached a stable version.

Totally! 😁
Thanks for your comprehension!
