### ISSUE TITLE
Add more documentations

### ISSUE THREAD

**Issue by curquiza** [meilisearch/instant-meilisearch#163]
This tool is not obvious to use and our users need more documentation about how to use Instant Search + instant-meilisearch. The sandbox is not enough.

Two steps:
1. Find a place for this kind of "tutorials": a `examples` folder? A longer README?
2. Write them

Here is a non-exhaustive list of the step 2:
- How to crop a field
- How to sort the facets (https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/#widget-param-sortby). See also: https://github.com/meilisearch/instant-meilisearch/issues/149.
- How to remove the zero facets count (https://www.algolia.com/doc/api-reference/widgets/refinement-list/js/#widget-param-transformitems). See: https://github.com/meilisearch/meilisearch-react/issues/5#issuecomment-732376287
- How to customize pagination (hits per page, number max of hits, number max of pages...)

⚠️ the meilisearch-react and meilisearch-vue demo might need the same docs! But let's start with this repo first.

**Comment by bidoubiwa** [comment]
- How to crop a field is fixed by #530 
- How to sort the facets: See issue #544 
- How to remove the zero facets count fixed by MeiliSearch, exception for the checked facets with a count of 0. They always appear see #458 
- How to customize pagination, is [this documentation](https://github.com/meilisearch/instant-meilisearch/#customization) enough or should we add more ?

**Comment by bidoubiwa** [comment]
@curquiza do you think more documentation is required?

**Comment by curquiza** [comment]
It's ok for me, but you are better than me now to say if it's enough or not 😊

**Comment by bidoubiwa** [comment]
I think it is enough, I hope so at least. Im closing this issue
