### ISSUE TITLE
NumberLocale option not working

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#424]
InstantSearch has an option called [`numberLocale`](https://www.algolia.com/doc/api-reference/widgets/instantsearch/js/#widget-param-numberlocale) that will format number based on the provided language code. 

Unfortunately since I couldn't make it work using [algoliasearch](https://github.com/algolia/algoliasearch-client-javascript) I cannot compare its compatibility with instantMeiliSearch. 

We should find how to make it work with algoliaSearch we can try it with instantMeiliSearch.

Here is an [react-instantSearch codesandbox](https://codesandbox.io/embed/github/algolia/doc-code-samples/tree/master/React+InstantSearch/getting-started) to try to make it work.

**Comment by sanders41** [comment]
As best as I can tell `numberLocale` is only used with the templating in `HoganHelpers` `helpers.formatNumber` like `{{#helpers.formatNumber}}{{count}}{{/helpers.formatNumber}}`, but I can't figure out how to how to use the templating. I am only making assumptions here because this is how I can find it being used in the tests. I can't find any reference at all on how to use the `numberLocale` or `formatNumber`.

In the React and Vue version I never can find any reference of `numberLocale` or `formatNumber` at all. Instead they always create a custom `formatNumber` function and use `toLocaleString()` with no parameters letting the system settings determine the format.

I'm not sure if this helps at all other than to say you aren't alone in not being able to figure it out 😄

**Comment by bidoubiwa** [comment]
Yes, this should be an issue in [instantSearch's repos](https://github.com/algolia/instantsearch.js), thanks a lot for trying!

**Comment by bidoubiwa** [comment]
Closing due to issue not being linked to instant-meilisearch
