### ISSUE TITLE
Missing searchable in refinements-list

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/instant-meilisearch#48]
When trying to use the `searchable` option in the `ais-refinement-list` it throws an error because the following method does not exist in `instant-meilisearch`: 

```bash
vue.runtime.esm.js?2b0e:1888 Error: search for facet values (searchable) was called, but this client does not have a function client.searchForFacetValues or client.initIndex(index).searchForFacetValues
```

Here is the documentation about `searchable` in refinement: 
https://www.algolia.com/doc/api-reference/widgets/refinement-list/vue/#widget-param-searchable

**Comment by curquiza** [comment]
Unfortunately, we will not able to implement this kind of feature until MeiliSearch handles a way to search in the facets in the core-engine part.
Indeed, Algolia has a `searchable` option you can set on the facets.

Seet the dashboard

<img width="745" alt="Capture d’écran 2020-08-20 à 17 33 20" src="https://user-images.githubusercontent.com/20380692/90793026-80024800-e30b-11ea-803d-c590c99ba842.png">

and the [associated documentation](https://www.algolia.com/doc/api-reference/api-parameters/attributesForFaceting/).

**Comment by haoyun** [comment]
because of the lack of `searchForFacetValues`, an `InstantMeiliSearchInstance` is not a `SearchClient` instance from `instantsearch.js`. 

https://github.com/meilisearch/instant-meilisearch/blob/a59ac0edbe46b9f8171e0b472ab0321da72de8d1/src/types/types.ts#L117-L122

https://github.com/algolia/instantsearch.js/blob/16cc34155d8af25893db3e521b4a1da26ce591e4/src/types/algoliasearch.ts#L33-L42
```
export type SearchClient = {
  search: DefaultSearchClient['search'];
  searchForFacetValues: DefaultSearchClient['searchForFacetValues'];
  addAlgoliaAgent?: DefaultSearchClient['addAlgoliaAgent'];
  initIndex?: (
    indexName: string
  ) => SearchIndex extends { findAnswers: any }
    ? Partial<Pick<SearchIndex, 'findAnswers'>>
    : SearchIndex;
};
```

On the other hand, `instantsearch()` function from `instantsearch.js` does expect a `SearchClient` instance.

https://github.com/algolia/instantsearch.js/blob/16cc34155d8af25893db3e521b4a1da26ce591e4/src/lib/InstantSearch.ts#L78
```
  searchClient: SearchClient; 
```

When using Typescript, this is a problem.

**Comment by bidoubiwa** [comment]
Hello @haoyun 
Until recentely `searchForFacetvalue` was optional in the SearchClient. I will add the method returning an empty response and raising a warning explaining why it does not work. 

Thanks so much for raising this :)

**Comment by bidoubiwa** [comment]
Closed as it will be added in instant-meilisearch once searching in facets is available in MeiliSearch

**Comment by electronick86** [comment]
Will this be implemented as Meilisearch 1.3 allows "SearchForFaceVelue"?

**Comment by Rigellute** [comment]
I would love this feature too, being able to search for facets is needed for my use-case.

**Comment by electronick86** [comment]
It's available with the last version of instant-meilisearch. You can see this behaviour on https://ecommerce.meilisearch.com/

There is just a bug that search for facet is not working when there is a sort.

**Comment by bidoubiwa** [comment]
Hey @electronick86, the bug is fixed ✨
