### ISSUE TITLE
Error when trying to search for facet using Menu component

### ISSUE THREAD

**Issue by mehmetron** [meilisearch/instant-meilisearch#481]
Error:
```
search for facet values (searchable) was called, but this client does not have a function client.searchForFacetValues or client.initIndex(index).searchForFacetValues

```
Here's a codesandbox. The error happens when you type in the search box on the left panel
https://codesandbox.io/s/elastic-joliot-dw7hk?file=/src/App.js

How do you solve this error?

**Comment by curquiza** [comment]
Since MeiliSearch cannot search in facet values (this is a feature of Algolia), instant-meilisearch cannot provide `searchForFacetValues`. The README.md of this repo describes all the compatibility, and this one is not available at the moment -> https://github.com/meilisearch/instant-meilisearch#-refinementlist
