### ISSUE TITLE
Cannot read property 'Readable' of undefined

### ISSUE THREAD

**Issue by kent1D** [meilisearch/instant-meilisearch#501]
Loading https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch@0.5.1/dist/instant-meilisearch.umd.js (same for the minified version) we obtain the following javascript error :  `Uncaught TypeError: Cannot read property 'Readable' of undefined`

It's followed by : `Uncaught ReferenceError: instantMeiliSearch is not defined`

Is it because of the use of "require" at the top of the file ?

Thanks in advances

**Comment by bidoubiwa** [comment]
hey @kent1D, thanks for raising this! The error came from changing the rollup typescript library with the official one that does not include node interop even while adding the option. 
I rolled back to the previous plugin and added some tests to ensure this should not happen again :) Thanks! 

fixed by #504
