### ISSUE TITLE
MeiliSearchApiError: Invalid JSON

### ISSUE THREAD

**Issue by ikramooe** [meilisearch/instant-meilisearch#516]
hello , 
i used the demo example and i'm getting this error 

MeiliSearchApiError: Invalid JSON: unknown field `filter`, expected one of `q`, `offset`, `limit`, `attributesToRetrieve`, `attributesToCrop`, `cropLength`, `attributesToHighlight`, `filters`, `matches`, `facetFilters`, `facetsDistribution` 

ANY HELP ?

**Comment by bidoubiwa** [comment]
Hello! Thanks for the issue :) 
This is because we need to release this PR to be compatible with MeiliSearch v0.22.0 #509
It should be released tonight or tomorrow!  meanwhile I would suggest you keep using meilisearch v0.21.0 or you use the branch `bump-meilisearch-v0.22.0` in your `package.json` 
like this: 

```
"instant-meilisearch": "meilisearch/instant-meilisearch#bump-meilisearch-v0.22.0",
```

In which case you can keep using meilisearch v0.22.0!

**Comment by bidoubiwa** [comment]
My bad, it seems that your error is due to the fact that you are still using meilisearch v0.20.0! Consider updating to v0.21.0 (or v0.22.0 as soon as we release the compatibility).

If you prefer not updating your MeiliSearch instance, you can rollback to the previous version of instant-meilisearch v0.5.1!

**Comment by bidoubiwa** [comment]
Can I assume this is fixed? If not reopen!
