### ISSUE TITLE
Pagination should cache hits from the first call

### ISSUE THREAD

**Issue by YikSanChan** [meilisearch/instant-meilisearch#520]
**Description**
I am using `SearchBox` and `Pagination` together.

**Expected behavior**
After the first call, since all the following calls are identical, the component can simply cache the first call results and reuse.

**Current behavior**
It sends `search` API call with param `limit=200` every time the user clicks the next page.

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
- Browser: [e.g. Chrome version 90.0]
- MeiliSearch version: v.0.21.0
- instant-meilisearch version: 0.5.2
- instantsearch.js version: v6.12.0

**Comment by bidoubiwa** [comment]
MeiliSearch does not provide the number of potentials hit after a search request. Because of that we enforce a hard limit on the number of hits that may be returned (see #18) to be able, on the pagination widget, to have a "last number". 

We need the a given limit to be able to have `>>` going to the last page.
ex: `<< < 1, 2, 3,.. > >>`

This limit can be improved or reduced [using the `hitsPerPage` option](https://github.com/meilisearch/instant-meilisearch#customization)!

The problem you encounter is that, if we put a hard limit on 200 hits, we still redo a search request on every change of page. 
That request useless as the first search request on the first page already provided the 200 potential hits. 

This issue can be solved by 
- Cache the results of the search request if it is not cached already
- Using the cache instead of doing a search request if there are cached hits for the provided search query

"pseudo code idea"

```js
if (Object.keys(cachedResults).includes(searchQuery) {
   searchResponse = cachedResults[searchQuery]
}
else {
 searchResponse =  // make search request 
 cachedResults[searchQuery] = response.hits
}
```

**Comment by bidoubiwa** [comment]
Working on it @YikSanChan if you want to take a look #533
