### ISSUE TITLE
Filter selection removes other filters, add OR in refinementsList

### ISSUE THREAD

**Issue by ThisIsMyFavouriteJar** [meilisearch/instant-meilisearch#599]
Hello, enjoying Meili quite a lot but running in the following issue.
I have a list of products, each with a single brand linked to it:

![image](https://user-images.githubusercontent.com/25418904/141487988-b05ce856-66dc-4dcf-9217-88ef1a1d5d54.png)

When I select a single filter everything works fine, but all other filterable options disappear immediately:
![image](https://user-images.githubusercontent.com/25418904/141488114-155ab3bc-370f-4ac2-b2a4-186f768cea4c.png)

Is it possible to select a filter, and still display all other filterable options? Basically enabling people
to select more than 1 brand and then applying an OR in the search? So after I selected Miele I still want
Siemens and Bosch and the other values be displayed!

Thank you!

**Comment by bidoubiwa** [comment]
Hello @ThisIsMyFavouriteJar 
This is something that needs to be implemented in instant-meilisearch! 

For the moment we only do `AND` but we should be able to retrieve the `OR` settings that can be passed on through here: 

- [RefinementList parameters](https://github.com/meilisearch/instant-meilisearch/blob/a944cd6807a5da346721d8d3f8f398a63e2b1e5d/README.md#-refinementlist)

**Comment by jasperjorna** [comment]
Hi @bidoubiwa,

Is this on the roadmap for the foreseeable future? And is there a possible way to work around this for now?

**Comment by bidoubiwa** [comment]
Unfortunately, I don't think it is possible. I have to finish some other tasks before I can look at this improvement. 
If you want to make a contribution I can help you in the process and show you where things should be changed

**Comment by dezyh** [comment]
Hey, I would be interested in working on this feature if no work has been started yet. Would appreciate any advise you have.

**Comment by bidoubiwa** [comment]
Hello @dezyh and @ThisIsMyFavouriteJar 

After rethinking about the problem their are two that are raised by this issue: 

## OR operator

I tried it again and in fact it works. I'm sorry for misleading you. You need to change the `operator` in your `refinmentList` widget. Example in react: 

```
<RefinementList attribute="genres" operator="or" />
```

## Do not hide the other values

This part may not be possible as it is due to MeiliSearch design. If you would like to see this options implemented in MeiliSearch could you start a discussion here: https://github.com/meilisearch/product/discussions/categories/feedback-feature-proposal. The designers of the API loves to receive feedback on how to help users get the results they want.

**Comment by gmourier** [comment]
Hi everyone! 👋

I've created a product discussion for that particular pain point [here](https://github.com/meilisearch/product/discussions/315). Feel free to add your hints and elaborate on this. 😇 

We are in the process of establishing the 2022 roadmap and we will certainly work on the facets. Thanks for your feedback.

**Comment by paligiannis** [comment]
@bidoubiwa it seems that even I apply operator="or" values start missing. Try with the brand facet [here](https://anelixi.com.gr/category/store/paidika-vrefika/paichnidia/paidika-paichnidia/paidika-pazl)

**Comment by bidoubiwa** [comment]
Hello yes, unfortunately this is disjonctive facet search when working between different facets. This is something that must be implemented either in instant meilisearch or meilisearch itself. I need to create a detailed issue explaining what needs to be done.

**Comment by paligiannis** [comment]
Hi @bidoubiwa i will someway implement if now and I will update you soon if there is any temp solution

**Comment by paligiannis** [comment]
@bidoubiwa Why on v0.6 seems that this is implemented? 
<img width="1064" alt="Screenshot 2022-03-14 at 10 52 11 AM" src="https://user-images.githubusercontent.com/10850092/158137729-78cd3108-528c-41f4-a53e-38eaddd2d48a.png">

**Comment by bidoubiwa** [comment]
Well it works in the simplified version of `OR` inside the same facet. For example lets say a cloths e-commerce.

You have two facets `type` and `color`. 
If in type you check `shoes` and `shirts`. With the `OR` operator you will receive both shirts and shoes.

But if you click on `color: red` the `OR` does not apply with `type`.  Between different facets it is always `AND`. 

Can you confirm @gmourier ?

**Comment by bidoubiwa** [comment]
Hello! When using `or` it is between two values. For example in a `product` facet if you click on both `shoes` and `shirts` you will see all documents containing both `shoes` or `shirts`. But all the other ones will be removed. 

What are you expecting? That the other fields stay but with a `0` value?

**Comment by paligiannis** [comment]
Hi! Yes, with or statement all values should be accessible to the user, to select for example the facet with value A, B, C, and all the values should remain in the facet area.

**Comment by bidoubiwa** [comment]
This should fix it #695

**Comment by paligiannis** [comment]
I see that you are preparing a new pull request and I was wondering from the first place how is that possible for the user to select other value if the values got hidden.

**Comment by bidoubiwa** [comment]
I'm providing this solution as a work-around for Meilisearch's behaviour.
As this is a decision from the Meilisearch engine itself. I suppose that if a value is at `0` there will be no effect on selecting that value. While if the value is still visible that means that there is at least one document, thus selecting that value adds search results. 
It is a practice often seen in websites I suppose because it reduces the attributes number and makes it easier for the user to see the options still relevant in its current search. 

@gmourier could give a better explanation.

**Comment by bidoubiwa** [comment]
Keeping this open to keep track of disjunctive facet search

**Comment by ar-siddiqui** [comment]
In our use case, we do not like the meilisearch API not returning 0 facets. We want to show users to see 0 value facets as well so that they can select them. The hack provided by this https://github.com/meilisearch/instant-meilisearch/pull/695 only works when you first do a no filter search, if you directly use a URL with specific rules it would not showcase them as the client does not have anything to remember from.

IMO the meilisearch API should always return 0 facets (or be configurable to return 0 facets) and the client could be configured to either display them or not.

For example, displaying 0 facets allow a user to add spreadsheet as well to the search
![image](https://user-images.githubusercontent.com/53625184/184213982-8855e620-9ca5-42af-9dc4-b3f6d4b010c2.png)

But without 0 facets, the user is not even aware that a type spreadsheet exists.
![image](https://user-images.githubusercontent.com/53625184/184213994-b6697819-e70b-44af-8eff-38e5c8345a00.png)

**Comment by bidoubiwa** [comment]
Hello @ar-siddiqui did you add `keepZeroFacets` in your instant meilisearch options?

**Comment by ar-siddiqui** [comment]
> Hello @ar-siddiqui did you add `keepZeroFacets` in your instant meilisearch options?

I am using react and it keepZeroFacets are not making any difference.

**Comment by bidoubiwa** [comment]
Are you using placeholderSearch at false?

**Comment by ar-siddiqui** [comment]
> Are you using placeholderSearch at false?

No, placeholderSearch is true

**Comment by bidoubiwa** [comment]
This is the issue, I'll be working on it soon enough and come back to you :)

**Comment by ar-siddiqui** [comment]
> This is the issue, I'll be working on it soon enough and come back to you :) Could you open an issue that states that `keepZeroFacets` does not work correctly when `placeHolderSearch` is set to false?

placeHolderSearch is true not false

**Comment by bidoubiwa** [comment]
My bad

> The hack provided by this https://github.com/meilisearch/instant-meilisearch/pull/695 only works when you first do a no filter search, if you directly use a URL with specific rules it would not showcase them as the client does not have anything to remember from.

This is the issue. Im currently working on the fix.
Anyway, can you open an issue on the subject? As this issue is not related to your issue. I will be removing the comments made above.

**Comment by ar-siddiqui** [comment]
> My bad
> 
> > The hack provided by this #695 only works when you first do a no filter search, if you directly use a URL with specific rules it would not showcase them as the client does not have anything to remember from.
> 
> This is the issue. Im currently working on the fix. Anyway, can you open an issue on the subject? As this issue is not related to your issue. I will be removing the comments made above.

https://github.com/meilisearch/instant-meilisearch/issues/825

**Comment by bidoubiwa** [comment]
The disjunctive search beta is released! Can you try it out? It is published on npm [here](https://www.npmjs.com/package/@meilisearch/instant-meilisearch/v/0.10.1-multi-index-search.0)

**Comment by bidoubiwa** [comment]
I suppose it answered your needs :)
