### ISSUE TITLE
Transpilation Required When Using Nuxt?

### ISSUE THREAD

**Issue by Tocas97** [meilisearch/instant-meilisearch#634]
Hi everyone! 
Apologies in advance if this is not the correct place to post this, but I don't really know where else to write this.

I'm currently working on a Nuxt-based project and I'm using this to build a search component. 
For performance reasons, I want to take advantage of Nuxt's SSR capabilities to get a few search results up front and then let the client handle any future searches. 
I've gotten this to work, but it wasn't necessarily smooth. I followed Algolia's documentation on setting SSR in Nuxt ([here](https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/vue/#with-nuxt)) which ended up being relatively straightforward. The problem was, though, whenever I tried to get results pre-rendered from the server I ended up getting an error saying that ```XMLHttpRequest is not defined```.
After a little digging I found out that that was because Nuxt/Webpack was getting the module from ```instant-meilisearch.umd.js``` which does indeed use ```XMLHttpRequest```.  I ended up solving this by going into my ```nuxt.config.js``` file and adding this package to the ```build.transpile``` property, as such:

```
 build: {

    // InstantSearch code uses ES modules, yet it needs to be executed in Node.js.
    // That’s why we need to let Nuxt know that those files should be transpiled during the build.
    // More info here: https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/vue/#with-nuxt
    transpile: ["vue-instantsearch", "instantsearch.js/es", "@meilisearch/instant-meilisearch"]
}
```

The first two properties are there as per Algolia's documentation, but I must admit that the last one was from trial and error. Which finally leads me to my question: is this what I should actually be doing to get this module to work for me? Or should I be doing something else?

Any input on this would be much appreciated 😊

Thanks!

**Comment by bidoubiwa** [comment]
Hello @Tocas97 
I'm very sorry for the delay I was on sick leave. I'll come back to you asap with an answer.

**Comment by Tocas97** [comment]
Hi @bidoubiwa! 
Hope you're doing better now 😊
Thanks for checking this out and getting back to me

**Comment by bidoubiwa** [comment]
> After a little digging I found out that that was because Nuxt/Webpack was getting the module from instant-meilisearch.umd.js which does indeed use XMLHttpRequest. 


First thing is that the instant-meilisearch package should provide by default the path to its un-builded source code. Which is not the case today as I naively put the `umd` build as the default built:

package.json
```json
  "main": "./dist/instant-meilisearch.umd.js",
```

If I change this to the following

```json
  "main": "./dist/src",
```
It provides a non-builted source code that can then be compiled by your environment however you require it. For example, in your case, node-oriented. 

Now, the reason why I provided `umd` by default at the time, is that `umd` works on almost all js environments. Thus node and browser.

The fact that you receive `XMLHttpRequest is not defined` is very weird as inside the `umd` it specifically compares the environments to know if it should use `XMLHttpRequest` or `node-fetch`. So indeed `XMLHttpRequest` exists inside the umd file, but it should never come to this line if the script is ran in a Node.JS environment. 

Nonetheless, I think it should be fixed by changing the default build I provide.

Thanks a lot for this issue, it will help greatly when I'll be working on changing this behavior.

**Comment by bidoubiwa** [comment]
Hey @Tocas97, if you have time could you try again to see if the problem has been solved?

**Comment by bidoubiwa** [comment]
I'm closing this issue, if it is not resolved yet feel free to re-open :)
