### ISSUE TITLE
"or" operator doesn't seem to work within a refinement list (disjunctive facet search).

### ISSUE THREAD

**Issue by alcanari** [meilisearch/instant-meilisearch#789]
Hi 👋

**Description**

"or" operator don't work within a refinement list.

**Current behavior**

When I click on a refinement list, only the options that have a document in common with the option selected are shown - even if the refinement list is set with the "or" operator.

So - when I have a refinement list with exclusive options (ie. none is shared by a document - in a belong_to/has_one association), I can only display a single option within the refinement list.

But - with the "or" operator, I'd like to see other options as well that I can select, so I can select two different options from the refinement list and see the documents that have either one or the other. 

**Screenshots or Logs**

```
      searchBrands.addWidget(
        panelForIndustries({
          container: "#categories",
          attribute: "industry.name",
          showMore: true,
          autoHideContainer: true,
          keepZeroFacets: true,
          operator: "or"
        })
      );

```

Behaviour - I have industries to search on brands. Each brand can only have one industry.

Before selecting anything:

![Screenshot 2022-07-04 at 23 41 53](https://user-images.githubusercontent.com/14922595/177223299-e3febb35-f10f-4d41-af0c-e72c2d69d4db.png)

Here's what I'd like as a result (using Algolia, which set the default operator as "or" - so I can select and view results from two different industries - as I would expect using the "or" attribute)

![Screenshot 2022-07-04 at 23 41 59](https://user-images.githubusercontent.com/14922595/177223383-3b3874fa-36d9-4680-ad41-d6da7d78fa90.png)

Here's the actual result by Meilisearch (the default operator being "and" - and the setting in the RefinementList doesn't seem to work)

![Screenshot 2022-07-04 at 23 42 05](https://user-images.githubusercontent.com/14922595/177223390-56e06220-86b6-4087-b3c3-717cc611cec9.png)

**Environment (please complete the following information):**
- Meilisearch version: MeiliSearch 0.27.1
- instant-meilisearch version: https://cdn.jsdelivr.net/npm/@meilisearch/instant-meilisearch/dist/instant-meilisearch.umd.min.js
- instantsearch.js version: InstantSearch.js 4.43.0

**Comment by bidoubiwa** [comment]
Hey @alcanari 
Unfortunately, the way it works today is that if you are doing `and` you have the following results: 

<img width="192" alt="Screenshot 2022-07-06 at 12 26 32" src="https://user-images.githubusercontent.com/33010418/177529933-bd415a65-7164-4f07-9e56-096e583e6411.png">
<img width="161" alt="Screenshot 2022-07-06 at 12 26 37" src="https://user-images.githubusercontent.com/33010418/177529940-10bcecbe-3cc9-4783-868f-9f6869bb8047.png">

and if you're using `or` you have the following: 

<img width="179" alt="Screenshot 2022-07-06 at 12 27 24" src="https://user-images.githubusercontent.com/33010418/177530093-42810bd8-2858-4419-8841-b3df856da07e.png">
<img width="177" alt="Screenshot 2022-07-06 at 12 27 26" src="https://user-images.githubusercontent.com/33010418/177530096-4798c1a5-e77c-4286-844f-64ce29883f0e.png">


I agree with you that this is counterintuitive! It is planned to update this behavior to what we call `disjunctive facet search`. 
When the next release of meilisearch (the engine) is out, I will be working on `instant-meilisearch` and on this issue as well. 
It should come in the following weeks. 
I will keep you updated once the issue is created on how `disjunctive facet search` works and if it seems to be what you are looking for. 

meanwhile, can I suggest using [`keepZeroFacet`](https://github.com/meilisearch/instant-meilisearch#keep-zero-facets) option which at least will still showcase your other facets!

**Comment by alcanari** [comment]
Hey, 

Thank you. I'm not sure I follow. In your examples, you have 3 games that are both Multiplayer and Single Player? If you'd only have games that would be Multiplayer or Single Player (none can be both) - would other facets show up on the using `or`?

Just to make sure I undestand, because I'm already using the [keepZeroFacet](https://github.com/meilisearch/instant-meilisearch#keep-zero-facets) option :)

**Comment by alcanari** [comment]
When you say "this is counterintuitive" -> you mean, the fact that you go from 3 to 7 for Single Player games in the using `or` option?

**Comment by bidoubiwa** [comment]
> When you say "this is counterintuitive" -> you mean, the fact that you go from 3 to 7 for Single Player games in the using or option?

Yes ! My bad  I wasn't very clear

**Comment by alcanari** [comment]
Thank you! 

Yes agreed - I understand it's related to the `disjunctive facet search` - got it. Just to be 100% clear - the `or` option on the refinement list right now changes the results of the search, but not the available options to select for now? :)

Also, did you saw my previous message? We're already using `keepZeroFacets` but it doesn't seem to work, which makes it hard to use in a setup where there are exclusive refinement lists options.

> Hey,
> 
> Thank you @bidoubiwa ! :)
> 
> I'm not sure I follow. In your examples, you have 3 games that are both Multiplayer and Single Player? If you'd only have games that would be Multiplayer or Single Player (none can be both) - would other facets show up when you're using `or`?
> 
> Just to make sure I understand, because I'm already using the [keepZeroFacet](https://github.com/meilisearch/instant-meilisearch#keep-zero-facets) option :)

**Comment by johnwbaxter** [comment]
Is there any idea of when this issue will be resolved? Thanks!

**Comment by bidoubiwa** [comment]
Hello @johnwbaxter 
I cannot guarantee any time for the moment unfortunately :/ I will try to create the issue explaining in details how it should be implemented asap so that contributors may implement it if they want it to be released sooner

**Comment by LiquidITGuy** [comment]
I add a flag on this (we add [keepZeroFacets](https://www.npmjs.com/package/@meilisearch/instant-meilisearch#keep-zero-facets) on configuration for the moment but i'm really interesting on that behaviour

**Comment by jeremylynch** [comment]
Would be great to keep moving forward on this where possible, this is a critical feature for us

**Comment by ar-siddiqui** [comment]
This is a pain point for us too.

We have "or" based filter

This is the `refinement list` without any filters

![image](https://user-images.githubusercontent.com/53625184/189965454-b8ef2b99-2425-44dd-9289-94c83d0be728.png)

When we select 1 this is what we would see (notice other options becoming `0`)
![image](https://user-images.githubusercontent.com/53625184/189965594-2b0ca457-cf3b-41d9-af73-708527ab913e.png)

But in fact, the `document` count available is not `0` but `6` since this is an "or" based filter. When we select `document` as well, our total search hits become 10 (6+4):

![image](https://user-images.githubusercontent.com/53625184/189965827-64e75302-d636-44b0-b4c8-7284a300618a.png)


This is what we expect to see: (filter count available, not filter count in current hits)

![image](https://user-images.githubusercontent.com/53625184/189967076-4fcd9f7b-4f9f-4c8a-9d54-0f7f8e0e412f.png)

**Comment by jeremylynch** [comment]
Does anyone know when we will get an update on this one?

**Comment by bidoubiwa** [comment]
Hey @jeremylynch. It is the next task we are working on :) I'll keep you updated

**Comment by kamopeter** [comment]
Hello there,
I'd like to ask about this feature, is there any update with that?

**Comment by bidoubiwa** [comment]
Working on it for the moment! We have been slowed down with hacktoberfest unfortunately

**Comment by anthonycook** [comment]
> Working on it for the moment! We have been slowed down with hacktoberfest unfortunately

Hi @bidoubiwa, any update on this? 

Happy to test on our 20k+ product database which has lots of facets if it helps.

**Comment by bidoubiwa** [comment]
Hey @anthonycook, I'm currently working on it :) Both multi-index search and disjunctive facet search are being added simultaneously.

You can follow along #888 Which introduces the multi-index search, and should be a gate opener to adding disjunctive very efficiently

**Comment by anthonycook** [comment]
> Hey @anthonycook, I'm currently working on it :) Both multi-index search and disjunctive facet search are being added simultaneously.
> 
> You can follow along #888 Which introduces the multi-index search, and should be a gate opener to adding disjunctive very efficiently

Amazing! Thanks for the update, I will follow along 😊

**Comment by alcanari** [comment]
Thank you for the update @bidoubiwa !

**Comment by kamopeter** [comment]
Sorry for my question, and maybe it's a stupid question, but when will this feature be available, would be happy to use it in existing project.
Thanks!

**Comment by bidoubiwa** [comment]
Hey @kamopeter 
The beta should be released this week on npm

**Comment by kamopeter** [comment]
Thanks! :)

**Comment by bidoubiwa** [comment]
The disjunctive search beta is released! Can you try it out? It is published on npm [here](https://www.npmjs.com/package/@meilisearch/instant-meilisearch/v/0.10.1-multi-index-search.0)

**Comment by bidoubiwa** [comment]
It is released on the latest dist tag in npm and should be acting as expected with v0.11.0!
